webreg/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views import defaults as default_views
from django.conf.urls.static import static
from main.urls import apiurlpatterns as mainapiurlpatterns
from main.urls import urlpatterns as main_urlpatterns
from patient_writer.urls import apiurlpatterns as patient_writer_apiurlpatterns

apiurlpatterns = mainapiurlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pwriter/', include('patient_writer.urls', namespace="patient_writer")),
    url(r'^infomat_writer/', include('infomat_writer.urls', namespace="infomat_writer")),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'api/', include(apiurlpatterns)),
    url(r'api/pwriter/', include(patient_writer_apiurlpatterns))
] + main_urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

webreg/infomat_writer/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.decorators.clickjacking import xframe_options_exempt
from infomat_writer.views import PatientWriteFirstStep, PatientWriteSecondStep, Confirm,\
    TalonView, logout






urlpatterns = [
    url(r'^input_first_step/(?P<department>[\d+]+)/$', xframe_options_exempt(PatientWriteFirstStep.as_view()), name="input_first_step"),
    url(r'^input_second_step/$', xframe_options_exempt(PatientWriteSecondStep.as_view()), name="input_second_step"),
    url(r'^confirm/$', xframe_options_exempt(Confirm.as_view()), name="confirm"),
    url(r'^agreement/$', xframe_options_exempt(TemplateView.as_view(template_name="infomat_writer/agreement.html")), name="agreement"),
    url(r'^talon/$', xframe_options_exempt(TalonView.as_view()), name="talon"),
    url(r'^accounts/logout/$', xframe_options_exempt(logout),
        {
            'template_name': "infomat_writer/logout.html",
        },
        name="account_logout"),
]

webreg/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import login, logout, password_reset
from main.api.timetable import SpecialistsFreeCells, SpecialistAllCells
from main.forms import AuthenticationForm
from main.views import MainView

apiurlpatterns = [
    url(r'timetable/free/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})$', SpecialistsFreeCells.as_view()),
    url(r'timetable/free/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})/(\d{1,4})$', SpecialistsFreeCells.as_view()),
    url(r'timetable/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})$', SpecialistAllCells.as_view())
]


urlpatterns = [
    url(r'^$', MainView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^accounts/login', login, {'template_name': "account/login.html",
                                    'authentication_form': AuthenticationForm,
                                    'extra_context': {'redirect_field_value': '/',
                                                      'redirect_field_name': 'next'}}, name="account_login"),
    url(r'^accounts/logout', logout, {'template_name': "account/logout.html",
                                      'extra_context': {'redirect_field_value': '/',
                                                        'redirect_field_name': 'next'}
                                      }, name="account_logout"),
]

webreg/patient_writer/accounts/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import views as auth_views
from patient_writer.accounts.forms import PatientRegistrationForm
from patient_writer.accounts.views import PatientRegistrationView, PatientActivationView, login, logout, \
    LogOutConfirmView

urlpatterns = [
    url(r'^accounts/register/$', PatientRegistrationView.as_view(
            disallowed_url=reverse_lazy('patient_writer:registration_disallowed'),
            template_name='patient_writer/accounts/register.html',
            form_class=PatientRegistrationForm,
            success_url=reverse_lazy('patient_writer:registration_complete')
            ),
        name="registration"),
    url(r'^accounts/register/complete',
        TemplateView.as_view(template_name="patient_writer/accounts/registration_complete.html"),
        name="registration_complete"),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', PatientActivationView.as_view(
            template_name='patient_writer/accounts/activate.html',
            ),
        name='registration_activate'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(
        template_name='patient_writer/activation_complete.html'),
        name='activation_complete'),

    url(r'^accounts/login', login,
        {
            'template_name': "patient_writer/accounts/login.html",
            'authentication_form': AuthenticationForm,
            'extra_context': {
                'redirect_field_value': reverse_lazy('patient_writer:input_second_step'),
                'redirect_field_name': 'next'
            }
        },
        name="account_login"),

    url(r'^accounts/logout/$', logout,
        {
            'template_name': "patient_writer/accounts/logout.html",
            'extra_context': {
                'redirect_field_value': reverse_lazy('patient_writer:input_first_step'),
                'redirect_field_name': 'next'
            }
        },
        name="account_logout"),

    url(r'^accounts/logout-confirm/$', LogOutConfirmView.as_view(), name="account_logout_confirm"),

    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'patient_writer:auth_password_reset_done',
         'email_template_name': 'patient_writer/accounts/email/password_reset_email.html',
         'html_email_template_name': 'patient_writer/accounts/email/password_reset_email.html',
         'subject_template_name': 'patient_writer/accounts/email/password_reset_subject.txt',
         'template_name': 'patient_writer/accounts/password_reset_form.html'},
        name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'patient_writer:auth_password_reset_complete',
         'template_name': 'patient_writer/accounts/password_reset_confirm.html'},
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        {'template_name': 'patient_writer/accounts/password_reset_complete.html'},
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        {'template_name': 'patient_writer/accounts/password_reset_done.html'},
        name='auth_password_reset_done'),
]

webreg/patient_writer/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from patient_writer.views import PatientWriteFirstStep, PatientWriteSecondStep, Confirm,\
    SpecialistTimeTable, TalonView, TalonPdf, AppointmentListView, HelpView, AppointmentDetailView,\
    CancelAppointmentView, SelectClinicView
from patient_writer.api.api import AvailableSpecialists, AvailableSpecializaionsForDepartment
from patient_writer.accounts.urls import urlpatterns as account_urlpatterns


apiurlpatterns = [
    url(r'^avail_specialists/(?P<department_id>\d+)/(?P<specialization_id>\d+)', AvailableSpecialists.as_view()),
    url(r'^specializations_for_dep/(\d+)', AvailableSpecializaionsForDepartment.as_view()),
]


urlpatterns = [
    url(r'^input_first_step/', PatientWriteFirstStep.as_view(), name="input_first_step"),
    url(r'^select_clinic/', SelectClinicView.as_view(), name="select_clinic"),
    url(r'^input_second_step/$', PatientWriteSecondStep.as_view(), name="input_second_step"),
    url(r'^agreement/$', TemplateView.as_view(template_name="patient_writer/agreement.html"), name="agreement"),
    url(r'^confirm/$', Confirm.as_view(), name="confirm"),
    url(r'^timetable/specialist/(\d+)', SpecialistTimeTable.as_view()),
    url(r'^talon/$', TalonView.as_view(), name="talon"),
    url(r'^talon_pdf/(\d+)$', TalonPdf.as_view(), name="talon_pdf"),
    url(r'^appointment_list/', AppointmentListView.as_view(), name="appointment_list"),
    url(r'^help/$', HelpView.as_view(), name="help"),
    url(r'^cancel_appointment/(?P<pk>\d+)', CancelAppointmentView.as_view(), name="cancel_appointment"),
    url(r'^appointment_detail/(?P<pk>\d+)', AppointmentDetailView.as_view(), name="appointment_detail"),
]

urlpatterns += account_urlpatterns

webreg/patient_writer/accounts/models.py
from registration.models import RegistrationProfile
from django.template.loader import render_to_string
from django.conf import settings


class PatientRegistrationProfile(RegistrationProfile):
    def send_activation_email(self, site):
        """
        Send an activation email to the user associated with this
        ``RegistrationProfile``.

        """
        ctx_dict = {'activation_key': self.activation_key,
                    'expiration_days': settings.ACCOUNT_ACTIVATION_DAYS,
                    'user': self.user,
                    'site': site}
        subject = render_to_string('patient_writer/accounts/email/activation_email_subject.txt',
                                   ctx_dict)
        # Force subject to a single line to avoid header-injection
        # issues.
        subject = ''.join(subject.splitlines())
        message = render_to_string('patient_writer/accounts/email/activation_email.html',
                                   ctx_dict)
        self.user.email_user(subject, '', settings.DEFAULT_FROM_EMAIL, html_message=message)

    class Meta:
        proxy = True

webreg/patient_writer/models.py
import datetime
from django.db import models


class SlotTypeConfig(models.Model):
    slot_type = models.OneToOneField(
        'main.SlotType', verbose_name="Тип слота"
    )
    min_age = models.PositiveIntegerField(
        default=0, verbose_name="Минимальный возраст"
    )
    max_age = models.PositiveIntegerField(
        default=200, verbose_name="Максимальный возраст"
    )

    class Meta:
        verbose_name = "Настройки типа слота"
        verbose_name_plural = "Настройки типов слотов"


class SpecializationConfig(models.Model):
    specialization = models.ForeignKey(
        "main.Specialization", verbose_name="Специализация"
    )
    department_config = models.ForeignKey(
        'patient_writer.DepartmentConfig'
    )
    slot_types = models.ManyToManyField(
        "main.SlotType", verbose_name="Разрешенные типы слотов"
    )
    service = models.ForeignKey(
        "main.Service",
        verbose_name="Назначаемая услуга",
    )
    enable = models.BooleanField(
        default=True, verbose_name="Вкл"
    )
    is_show_comment = models.BooleanField(
        default=False, verbose_name='Вывод комментария'
    )
    comment = models.CharField(
        max_length=512, verbose_name='Комментарий', blank=True, null=True
    )

    class Meta:
        unique_together = ('specialization', 'department_config')
        verbose_name = "Настройки для специализации"
        verbose_name_plural = "Настройки для специализаций"


class SpecialistConfig(models.Model):
    specialist = models.OneToOneField(
        "main.Specialist",
        verbose_name="Specialist"
    )
    service = models.ForeignKey(
        "main.Service",
        verbose_name="Услуга для назначения",
        null=True, blank=True,
        related_name="first_service_specialist"
    )
    service2 = models.ForeignKey(
        "main.Service",
        verbose_name="Услуга повторного приема",
        null=True, blank=True,
        related_name="second_service_specialist"
    )

    def __str__(self):
        return self.specialist.fio

    class Meta:
        verbose_name = "Настройки для специалиста"
        verbose_name_plural = "Настройки для специалистов"


class ClinicConfig(models.Model):
    clinic = models.OneToOneField(
        'main.Clinic', verbose_name="Мед. учреждение"
    )
    sms = models.BooleanField(
        default=True, verbose_name='SMS-уведомления'
    )
    phone = models.CharField(
        max_length=127, verbose_name='Телефон для отказов'
    )
    phone2 = models.CharField(
        max_length=127, verbose_name='Телефон для информирования'
    )
    logo = models.ImageField(
        verbose_name='Логотип', blank=True, null=True, upload_to='logos'
    )
    send_sms = models.BooleanField(
        verbose_name="Посылать СМС ?", default=True
    )
    find_only_attached = models.BooleanField(
        verbose_name="Искать только прикрепленных пациентов",
        default=True
    )

    def __str__(self):
        return self.clinic.name

    class Meta:
        verbose_name = "Настройки мед. учреждения"
        verbose_name_plural = "Настройки мед. учреждений"


class DepartmentConfig(models.Model):
    department = models.OneToOneField(
        'main.Department', verbose_name="Подразделение"
    )
    specializations = models.ManyToManyField(
        'main.Specialization', through=SpecializationConfig
    )
    day_start_offset = models.PositiveIntegerField(
        default=1, verbose_name='Отступ начала записи'
    )
    today_time_interval = models.PositiveIntegerField(
        default=60, verbose_name='Защитный интервал записи в текущий день',
        help_text='Минуты'
    )
    day_range = models.PositiveIntegerField(
        default=0, verbose_name='Период записи'
    )
    phone = models.CharField(
        max_length=31, verbose_name='Телефон для отказов', blank=True, null=True
    )
    phone2 = models.CharField(
        max_length=31, verbose_name='Телефон для информирования', blank=True, null=True
    )
    min_age = models.PositiveIntegerField(
        default=0, verbose_name='Минимальный возраст'
    )
    max_age = models.PositiveIntegerField(
        default=200, verbose_name='Максимальный возраст'
    )
    order = models.PositiveIntegerField(
        verbose_name="Порядок", default=0,
    )

    def __str__(self):
        return '{0}, {1}'.format(self.department.name, self.department.address)

    def save(self, *args, **kwargs):
        if self.day_start_offset > self.day_range:
            self.day_start_offset = self.day_range
        super(DepartmentConfig, self).save(*args, **kwargs)

    def get_date_range(self):
        start_date = datetime.date.today() + datetime.timedelta(self.day_start_offset)
        end_date = datetime.date.today() + datetime.timedelta(self.day_range)
        return start_date, end_date

    class Meta:
        verbose_name = 'Настройки подразделения'
        verbose_name_plural = 'Настройки подразделений'

webreg/patient_writer/templates/patient_writer/agreement.html
{% extends 'patient_writer/base.html' %}
{% load flatblocks %}
{% block content %}
  <div id="agreement" class="container-fluid has-frame">
    <div class="row">
      <div class="col-xs-12 ">
        <h2>Согласие на обработку персональных данных</h2>
        {% flatblock "agreement"%}
      </div>
    </div>
    <div class="row col-xs-12 col-sm-6 col-sm-offset-3">
      <div>
        <a class="btn btn-primary btn-lg btn-block form-btn" href="{{ request.META.HTTP_REFERER }}"><span class="glyphicon glyphicon-chevron-left"></span>Назад</a>
      </div>
    </div>
  </div>

{% endblock content %}

webreg/patient_writer/templates/patient_writer/appointment_list.html
{% extends 'patient_writer/base.html' %}
{% load static %}
{% load compress %}
{% load filters %}


{% block css %}
  {{block.super}}
  {% compress css %}
  <link rel="stylesheet" href="{% static 'css/appointment_list.css' %}"/>
  {% endcompress %}
{% endblock %}

{% block content %}
<table class="table" id="appointment-list-table">
    <thead>
        <tr>
            <th >дата приема</th>
            <th>время приема</th>
            <th class="hidden-xs">подразделение</th>
            <th class="hidden-xs">специалист</th>
            <th class="hidden-xs">специальность</th>
            <th class="hidden-xs">дата записи</th>
            <th> отменить</th>
        </tr>
    </thead>
    <tbody>
        {% for appointment in object_list %}
          <tr  href="{% url 'patient_writer:appointment_detail' pk=appointment.id %}" class="clickable-row {% if not appointment.date|date_gt %}active{% endif %} {% if appointment.deleted %}danger{% endif %}">
             <td>{{ appointment.date }}</td>
              <td>{{ appointment.cell.time_start }}</td>
              <td class="hidden-xs">{{ appointment.specialist.department.name }}<br>{{ appointment.specialist.department.address }}</td>
              <td class="hidden-xs">{{ appointment.specialist }}</td>
              <td class="hidden-xs">{{ appointment.specialist.specialization }}</td>
              <td class="hidden-xs">{{ appointment.created_time.astimezone }}</td>
              <td class="margin-auto">
                {% if appointment.date|date_gt and not appointment.deleted %}
                  <a href="{% url 'patient_writer:cancel_appointment' pk=appointment.id %}"><span class="glyphicon glyphicon-remove"></span></a>
                {% endif %}
                {% if appointment.deleted %}
                  <b>отменено</b>
                {% endif%}
              </td>
          </tr>
          <tr class="visible-xs {% if not appointment.date|date_gt %}active{% endif %} {% if appointment.deleted %}danger{% endif %}"><td colspan="3">{{ appointment.specialist }}</td></tr>
          <tr class="visible-xs {% if not appointment.date|date_gt %}active{% endif %} {% if appointment.deleted %}danger{% endif %}"><td colspan="3"> {{ appointment.specialist.specialization }}</td></tr>
          <tr class="visible-xs {% if not appointment.date|date_gt %}active{% endif %} {% if appointment.deleted %}danger{% endif %}"><td colspan="3"> <a href="{% url 'patient_writer:appointment_detail' pk=appointment.id %}" class="btn btn-primary">Подробности</a></td></tr>
          <tr class="visible-xs table-separator"><td colspan="3"></td></tr>
        {% endfor %}
    </tbody>
</table>

{% include "pagination.html" %}

{% endblock %}

{% block javascript %}
{{ block.super}}
  {% compress js %}
  <script src="{% static '/js/appointment_list.js' %}"></script>
  {% endcompress %}
{% endblock javascript%}

webreg/patient_writer/templates/patient_writer/base.html
{% extends 'base.html' %}

{% block navigation-panel %}
        <nav class="navbar navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <a class="navbar-brand" href="{% url 'patient_writer:input_first_step' %}"> <span class="glyphicon glyphicon-pencil"></span>Запись</a>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              {% if request.user.is_authenticated %}
                <a href="" class="visible-xs navbar-text">{{ patient.first_name }} {{patient.last_name.0}}. {{ patient.middle_name.0 }}.</a>
              {% endif %}
            </div>

            <div class="collapse navbar-collapse" id="main-navbar-collapse">
              {% comment %}
              <ul class="nav navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'patient_writer:help' %}">Помощь</a>
                </li>
              </ul>
              {% endcomment %}
              <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                <li class="nav-item navbar-right">
                  <a id="log-out-link" class="nav-link navbar-right"  href="{% url 'patient_writer:account_logout_confirm' %}"><span class="glyphicon glyphicon-log-out"></span> Выйти</a>
                </li>
                <li class="hidden-xs nav-item">
                    <a href="" class="nav-link">{{ patient.first_name }} {{patient.last_name.0}}. {{ patient.middle_name.0 }}.</a>
                </li>
                <li class="visible-xs nav-item">
                {% if patient %}
                    <a class="nav-link navbar-right" href="{% url 'patient_writer:appointment_list' %}"><span class="glyphicon glyphicon-th-list"></span> История записи</a>
                {% endif%}
                </li>
                {% else %}
                <li class="nav-item">
                  <a href="{% url 'patient_writer:registration' %}" class="nav-link">Регистрация</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'patient_writer:account_login' %}"><span class="glyphicon glyphicon-log-in"></span> Войти в личный кабинет</a>
                </li>
                {% endif %}
                <li class="visible-xs nav-item">
                  <a class="nav-link navbar-right"  href="#link2"><span class="glyphicon glyphicon-question-sign"></span> Вопросы и ответы</a>
                </li>
                <li class="visible-xs nav-item">
                  <a class="nav-link navbar-right" href="{% url 'patient_writer:agreement' %}"><span class="glyphicon glyphicon-list-alt"></span> Согласие на обработку ПД</a>
                </li>

              </ul>
            </div>
          </div>
        </nav>
{% endblock navigation-panel %}

{% block sidenavigation %}
{% if patient %}
<a class="hidden-xs list-group-item" href="{% url 'patient_writer:appointment_list' %}"><span class="glyphicon glyphicon-th-list"></span> История записи</a>
{% endif%}
<a class="hidden-xs list-group-item" href="#link2"><span class="glyphicon glyphicon-question-sign"></span> Вопросы и ответы</a>
<a class="hidden-xs list-group-item" href="{% url 'patient_writer:agreement' %}"><span class="glyphicon glyphicon-list-alt"></span> Согласие на обработку ПД</a>

{% endblock sidenavigation %}

webreg/patient_writer/templates/patient_writer/help.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

webreg/patient_writer/templates/patient_writer/input_second_step.html
{% extends 'patient_writer/base.html' %}

{% load flatblocks %}
{% load static %}
{% load compress %}

{% block content %}
<div class="container-fluid has-frame">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <h3>ВЫБЕРИТЕ ДАТУ И ВРЕМЯ</h3>
    <form id="input_form_2" method="POST" action="{% url 'patient_writer:input_second_step' %}">
      {% csrf_token %}
      <div id="department-form" class="form-group">
        <label for="id_department" class="control-label requiredField">
          Подразделение <span class="asteriskField">*</span>
        </label>
        <div>
          <select class="select form-control" id="id_department" name="department" required>
            <option disabled selected value=-1> -- Выберите подразделение -- </option>
            {% for department in departments %}
              <option value="{{department.id}}">{{department.name}}, {{department.address}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div id="speciality-form" class="form-group" style="display: none">
        <label for="id_speciality" class="control-label requiredField">
          Специальность <span class="asteriskField">*</span>
        </label>
        <select id="id_speciality" type="text" class="form-control" name="speciality" required>
          <option disabled selected value=-1> -- Выберите специальность -- </option>
        </select>
        <button id="speciality_question" class="hidden-xs btn btn-primary question-mark" type="button" data-toggle="modal" data-target="#speciality_help_modal">?</button>
        <div id="speciality_help_modal" class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
             <div class="modal-body">
                {% flatblock "speciality_help" %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="speciality-comment-message" class="alert" style="display: none">
      </div>
      <div id="specialist-form" class="form-group" style="display:none">
        <label for="id_specialist" class="control-label requiredField">
          Специалист <span class="asteriskField">*</span>
        </label>
        <select id="id_specialist" class="form-control" name="specialist" required>
          <option disabled selected value=-1> -- Выберите специалиста -- </option>
        </select>
        <button id="specialist_question" class="hidden-xs btn btn-primary question-mark" type="button" data-toggle="modal" data-target="#specialist_help_modal">?</button>
         <div id="specialist_help_modal" class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
             <div class="modal-body">
                {% flatblock "specialist_help" %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div id="timetable-form" class="row container-fluid form-group" style="display: none">
        <label>
          Выберите дату и время <span class="asteriskField">*</span>
        </label>
        <div class="has-border">
          <div id="id_selected_datetime" style="display: none;">
            <div class="row">
	            <label class="col-sm-5">
		            Дата приема:
              </label>
              <div class="col-sm-5 form-value">
                <div  id="id_selected_date">
                </div>
                <div  id="id_selected_dayweek">
                </div>
              </div>
            </div>
            <div class="row">
	            <label class="col-sm-5">
		            Время приема:
              </label>
              <div class = "col-xs-12 col-sm-5 form-value" id="id_selected_time">
              </div>
            </div>
          </div>
          <div class="row">
              <div class="col-sm-6 col-sm-offset-3">
                <button id="show-timetable-button" type="button" class="btn btn-primary btn-block">
                    ВЫБРАТЬ
                </button>
              </div>
          </div>
        </div>
        <input id="id_cell" type="hidden" name="cell">
        <div  class="modal fade" id="timetable-modal-window">
          <div>
            <div class="modal-content">
              <div class="modal-header">
                <div class="col-xs-4 col-xs-offset-4">
                  <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">
                    <span class="glyphicon glyphicon-chevron-left"></span>Назад
                  </button>
                </div>
              </div>
              <div id="id_loading_message" style="display: none">
                <h4>Загрузка расписания...</h4>
                <div class="loader">
                </div>
              </div>
              <div class="modal-body" id="id_timetable">
              </div>
              <div class="modal-footer">
                <div class="col-xs-4 col-xs-offset-4">
                  <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Закрыть</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="error-message" class="alert alert-danger" style="display:none;">
      </div>
     <div class="row col-xs-12 col-sm-6 col-sm-offset-3 form-btn">
      <a id="back-button" class="btn btn-primary btn-lg btn-block" href="{% url 'patient_writer:account_logout' %}"><span class="glyphicon glyphicon-chevron-left"></span> Назад</a>
      <button type="submit" id="write-button" class="btn btn-primary btn-lg btn-block" style="display: none">Записаться</button>
     </div>
      </form>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
{{ block.super}}
  <script type="text/javascript" src="{% static 'library/jquery-touchswipe/jquery.touchSwipe.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'library/jcarousel/dist/jquery.jcarousel.min.js' %}"></script>
  {% compress js %}
  <script type="text/javascript" src="{% static 'js/timetablecarousel.js' %}"></script>
  <script src="{% static '/js/input_second_form_control.js' %}"></script>
  {% endcompress %}
{% endblock javascript%}