webreg/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views import defaults as default_views
from django.conf.urls.static import static
from main.urls import apiurlpatterns as mainapiurlpatterns
from main.urls import urlpatterns as main_urlpatterns
from patient_writer.urls import apiurlpatterns as patient_writer_apiurlpatterns

apiurlpatterns = mainapiurlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pwriter/', include('patient_writer.urls', namespace="patient_writer")),
    url(r'^infomat_writer/', include('infomat_writer.urls', namespace="infomat_writer")),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'api/', include(apiurlpatterns)),
    url(r'api/pwriter/', include(patient_writer_apiurlpatterns))
] + main_urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

webreg/infomat_writer/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.decorators.clickjacking import xframe_options_exempt
from infomat_writer.views import PatientWriteFirstStep, PatientWriteSecondStep, Confirm,\
    TalonView, logout






urlpatterns = [
    url(r'^input_first_step/(?P<department>[\d+]+)/$', xframe_options_exempt(PatientWriteFirstStep.as_view()), name="input_first_step"),
    url(r'^input_second_step/$', xframe_options_exempt(PatientWriteSecondStep.as_view()), name="input_second_step"),
    url(r'^confirm/$', xframe_options_exempt(Confirm.as_view()), name="confirm"),
    url(r'^agreement/$', xframe_options_exempt(TemplateView.as_view(template_name="infomat_writer/agreement.html")), name="agreement"),
    url(r'^talon/$', xframe_options_exempt(TalonView.as_view()), name="talon"),
    url(r'^accounts/logout/$', xframe_options_exempt(logout),
        {
            'template_name': "infomat_writer/logout.html",
        },
        name="account_logout"),
]

webreg/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import login, logout, password_reset
from main.api.timetable import SpecialistsFreeCells, SpecialistAllCells
from main.forms import AuthenticationForm
from main.views import MainView

apiurlpatterns = [
    url(r'timetable/free/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})$', SpecialistsFreeCells.as_view()),
    url(r'timetable/free/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})/(\d{1,4})$', SpecialistsFreeCells.as_view()),
    url(r'timetable/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})$', SpecialistAllCells.as_view())
]


urlpatterns = [
    url(r'^$', MainView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^accounts/login', login, {'template_name': "account/login.html",
                                    'authentication_form': AuthenticationForm,
                                    'extra_context': {'redirect_field_value': '/',
                                                      'redirect_field_name': 'next'}}, name="account_login"),
    url(r'^accounts/logout', logout, {'template_name': "account/logout.html",
                                      'extra_context': {'redirect_field_value': '/',
                                                        'redirect_field_name': 'next'}
                                      }, name="account_logout"),
]

webreg/patient_writer/models.py
import datetime
from django.db import models


class SlotTypeConfig(models.Model):
    slot_type = models.OneToOneField(
        'main.SlotType', verbose_name="Тип слота"
    )
    min_age = models.PositiveIntegerField(
        default=0, verbose_name="Минимальный возраст"
    )
    max_age = models.PositiveIntegerField(
        default=200, verbose_name="Максимальный возраст"
    )

    class Meta:
        verbose_name = "Настройки типа слота"
        verbose_name_plural = "Настройки типов слотов"


class SpecializationConfig(models.Model):
    specialization = models.ForeignKey(
        "main.Specialization", verbose_name="Специализация"
    )
    department_config = models.ForeignKey(
        'patient_writer.DepartmentConfig'
    )
    slot_types = models.ManyToManyField(
        "main.SlotType", verbose_name="Разрешенные типы слотов"
    )
    service = models.ForeignKey(
        "main.Service",
        verbose_name="Назначаемая услуга",
    )
    enable = models.BooleanField(
        default=True, verbose_name="Вкл"
    )
    is_show_comment = models.BooleanField(
        default=False, verbose_name='Вывод комментария'
    )
    comment = models.CharField(
        max_length=512, verbose_name='Комментарий', blank=True, null=True
    )

    class Meta:
        unique_together = ('specialization', 'department_config')
        verbose_name = "Настройки для специализации"
        verbose_name_plural = "Настройки для специализаций"


class SpecialistConfig(models.Model):
    specialist = models.OneToOneField(
        "main.Specialist",
        verbose_name="Specialist"
    )
    service = models.ForeignKey(
        "main.Service",
        verbose_name="Услуга для назначения",
        null=True, blank=True,
        related_name="first_service_specialist"
    )
    service2 = models.ForeignKey(
        "main.Service",
        verbose_name="Услуга повторного приема",
        null=True, blank=True,
        related_name="second_service_specialist"
    )

    def __str__(self):
        return self.specialist.fio

    class Meta:
        verbose_name = "Настройки для специалиста"
        verbose_name_plural = "Настройки для специалистов"


class ClinicConfig(models.Model):
    clinic = models.OneToOneField(
        'main.Clinic', verbose_name="Мед. учреждение"
    )
    sms = models.BooleanField(
        default=True, verbose_name='SMS-уведомления'
    )
    phone = models.CharField(
        max_length=127, verbose_name='Телефон для отказов'
    )
    phone2 = models.CharField(
        max_length=127, verbose_name='Телефон для информирования'
    )
    logo = models.ImageField(
        verbose_name='Логотип', blank=True, null=True, upload_to='logos'
    )
    send_sms = models.BooleanField(
        verbose_name="Посылать СМС ?", default=True
    )
    find_only_attached = models.BooleanField(
        verbose_name="Искать только прикрепленных пациентов",
        default=True
    )

    def __str__(self):
        return self.clinic.name

    class Meta:
        verbose_name = "Настройки мед. учреждения"
        verbose_name_plural = "Настройки мед. учреждений"


class DepartmentConfig(models.Model):
    department = models.OneToOneField(
        'main.Department', verbose_name="Подразделение"
    )
    specializations = models.ManyToManyField(
        'main.Specialization', through=SpecializationConfig
    )
    day_start_offset = models.PositiveIntegerField(
        default=1, verbose_name='Отступ начала записи'
    )
    today_time_interval = models.PositiveIntegerField(
        default=60, verbose_name='Защитный интервал записи в текущий день',
        help_text='Минуты'
    )
    day_range = models.PositiveIntegerField(
        default=0, verbose_name='Период записи'
    )
    phone = models.CharField(
        max_length=31, verbose_name='Телефон для отказов', blank=True, null=True
    )
    phone2 = models.CharField(
        max_length=31, verbose_name='Телефон для информирования', blank=True, null=True
    )
    min_age = models.PositiveIntegerField(
        default=0, verbose_name='Минимальный возраст'
    )
    max_age = models.PositiveIntegerField(
        default=200, verbose_name='Максимальный возраст'
    )
    order = models.PositiveIntegerField(
        verbose_name="Порядок", default=0,
    )

    def __str__(self):
        return '{0}, {1}'.format(self.department.name, self.department.address)

    def save(self, *args, **kwargs):
        if self.day_start_offset > self.day_range:
            self.day_start_offset = self.day_range
        super(DepartmentConfig, self).save(*args, **kwargs)

    def get_date_range(self):
        start_date = datetime.date.today() + datetime.timedelta(self.day_start_offset)
        end_date = datetime.date.today() + datetime.timedelta(self.day_range)
        return start_date, end_date

    class Meta:
        verbose_name = 'Настройки подразделения'
        verbose_name_plural = 'Настройки подразделений'

webreg/infomat_writer/views.py
import datetime
from xhtml2pdf import pisa
import io
from wsgiref.util import FileWrapper

from django.db.models import Q
from django.http import StreamingHttpResponse, HttpResponse, Http404
from django.shortcuts import redirect
from django.views.generic import FormView, TemplateView, View, ListView, DetailView, DeleteView
from django.contrib.auth import login
from django.core.exceptions import PermissionDenied, ImproperlyConfigured
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.contrib.auth.views import login as DjangoLogin, logout as DjangoLogout
from patient_writer.forms import InputFirstStepForm
from patient_writer.models import DepartmentConfig, ClinicConfig, SpecializationConfig
from main.mixins import ProfileRequiredMixin
from main.logic import *
from patient_writer.logic import get_allowed_slot_types, get_specialist_service
from loghandle.models import UserAction as action


class Actions:
    AUTHENTICATION = 'Аутентификация'
    CONFIRM = 'Подтверждение пользователя'
    GET_DEPARTMENTS = 'Получение списка подразделений'
    GET_SPECIALITIES = 'Получение специальностей'
    GET_SPECIALISTS = 'Получение специалистов'
    GET_TIMETABLE = 'Получение расписания'
    CHECK_FREE_CELL = 'Проверка доступности ячейки'
    CREATE_APPOINTMENT = 'Создание назначения'
    GET_TALON = 'Получение талона'
    CANCEL_APPOINTMENT = 'Отмена записи'
    REGISTER = "Пользователь зарегистрировался"
    ACTIVE = "Пользователь стал активным"
    LOGIN = "Пользоваетль залогинился"
    LOGOUT = "Пользователь вышел"
    WRONG_PASSWORD = "Неверный пароль"


class PatientWriteFirstStep(FormView):
    template_name = 'infomat_writer/input_first_step.html'
    form_class = InputFirstStepForm
    success_url = reverse_lazy('infomat_writer:confirm')

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            login(request, form.get_user(), backend='main.authentication.PolisNumberBackend')

            # сохранение id пациента в сессии для последующих шагов
            request.session['patient_id'] = form.cleaned_data['patient_id']
            request.session['phone'] = form.cleaned_data['phone']
            action.log(Actions.AUTHENTICATION)

        return super(PatientWriteFirstStep, self).post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        request.session.flush()
        department_id = int(kwargs['department'])
        request.session['department_id'] = department_id
        print(department_id)
        try:
            department = Department.objects.get(id=department_id)
            request.session['clinic_id'] = department.clinic.id
        except Department.DoesNotExist:
            raise Http404
        return super(PatientWriteFirstStep, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        kwargs.update({'department_id': self.request.session['department_id']})
        return super(PatientWriteFirstStep, self).get_context_data(**kwargs)


class Confirm(TemplateView):
    template_name = 'infomat_writer/confirm.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        patient_id = request.session.get('patient_id', None)
        clinic_id = request.session.get('clinic_id', None)
        if not patient_id or not clinic_id:
            return redirect('infomat_writer:input_first_step', department=request.session['department_id'])
        try:
            patient = Patient.objects.get(id=patient_id)
        except Patient.DoesNotExist:
            return redirect('infomat_writer:input_first_step', department=request.session['department_id'])
        return self.render_to_response(context)


class PatientWriteSecondStep(ProfileRequiredMixin, TemplateView):
    template_name = 'infomat_writer/input_second_step.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        patient_id = request.session.get('patient_id', None)
        try:
            patient = Patient.objects.get(pk=patient_id)
        except Patient.DoesNotExist:
            return HttpResponse(status=500)
        # обновление телефона пациента
        phone = request.session.get('phone', None)
        if phone:
            update_patient_phone_number(patient, phone)
        if not patient_id:
            return redirect("infomat_writer:input_first_step", department=self.request.session['department_id'])
        action.log(Actions.CONFIRM)
        years_old = patient.age
        clinic_id = self.request.session['clinic_id']
        try:
            clinic = Clinic.objects.get(id=clinic_id)
        except Clinic.DoesNotExist:
            return redirect('infomat_writer:input_first_step', department=self.request.session['department_id'])

        departments = Department.objects.filter(
            clinic_id=clinic.id,
            departmentconfig__min_age__lte=years_old,
            departmentconfig__max_age__gte=years_old
        ).order_by('departmentconfig__order')
        context['departments'] = departments
        context['department_id'] = request.session.get('department_id', None)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        try:
            speciality_id = request.POST['speciality']
            specialist_id = request.POST['specialist']
            department_id = request.session['department_id']
            cell_id = request.POST['cell']
            patient_id = request.session['patient_id']
        except KeyError:
            redirect('infomat_writer:input_second_step')
        user_profile = request.user_profile
        cell = Cell.objects.get(id=cell_id)
        specialist = Specialist.objects.get(id=specialist_id)
        patient = Patient.objects.get(id=patient_id)
        department = Department.objects.get(id=department_id)
        allowed_slot_types = get_allowed_slot_types(user_profile, patient, department, specialist.specialization)
        if cell.slot_type.id not in allowed_slot_types:
            raise PermissionDenied("Нет доступных для назначения слотов")
        service = get_specialist_service(specialist)
        # Для специализации и специалиста обязательно должна быть настроена услуга
        if not service:
            raise ImproperlyConfigured("Для специализации и специалиста обязательно должна быть настроена услуга")
        request.session['cell_id'] = cell_id
        if request.session.get('error', None):
            del request.session['error']
        try:
            appointment = create_appointment(
                user_profile, patient, specialist, service, cell.date, cell
            )
            action.log(Actions.CREATE_APPOINTMENT)
            request.session['appointment_id'] = appointment.id
            appointment.send_sms()
        except AppointmentError as e:
            request.session['error'] = str(e)
            log.error(str(e))
        return redirect("infomat_writer:talon")


class TalonView(ProfileRequiredMixin, TemplateView):
    template_name = 'infomat_writer/talon.html'

    def get(self, request, *args, **kwargs):
        appointment_id = request.session.get('appointment_id', None)
        context = self.get_context_data(**kwargs)
        try:
            cell = Cell.objects.get(id=request.session['cell_id'])
        except Exception as e:
            context['error'] = str(e)
        context['error'] = request.session.get('error', None)
        context['cell'] = cell
        context['appointment_id'] = appointment_id
        return self.render_to_response(context)


def logout(request, *args, **kwargs):
    kwargs.update(
        {
            'next_page': '/infomat_writer/input_first_step/' + str(request.session['department_id']) + '/'
        },
    )
    action.log(Actions.LOGOUT)
    http = DjangoLogout(request, *args, **kwargs)
    try:
        del request.session['patient_id']
        del request.session['clinic_id']
    except KeyError:
        pass
    return http

webreg/infomat_writer/templates/infomat_writer/agreement.html
{% extends 'infomat_writer/base.html' %}
{% load flatblocks %}
{% block content %}
  <div id="agreement" class="container-fluid has-frame">
    <div class="row">
      <div class="col-xs-12 ">
        <h2>Согласие на обработку персональных данных</h2>
        {% flatblock "agreement"%}
      </div>
    </div>
    <div class="row col-xs-12 col-sm-6 col-sm-offset-3">
      <div>
        <a class="btn btn-primary btn-lg btn-block form-btn" href="{{ request.META.HTTP_REFERER }}"><span class="glyphicon glyphicon-chevron-left"></span>Назад</a>
      </div>
    </div>
  </div>

{% endblock content %}

webreg/infomat_writer/templates/infomat_writer/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
{% load flatblocks %}
{% load compress %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Запись на прием{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{% static 'library/html5shiv/dist/html5shiv.min.js' %}"></script>
    <![endif]-->


    {% block css %}
      <link rel="stylesheet" href="{% static 'library/bootstrap/dist/css/bootstrap.min.css' %}">
      <link rel="stylesheet" href="{% static 'library/keyboard/dist/css/keyboard.min.css' %}">
      {% compress css %}
      <!--
      <link rel="stylesheet" href="{% static 'css/bootstrapstyle.css' %}">
      //comment-->
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
      <link rel="stylesheet" href="{% static 'css/keyboard.css' %}">
      <link rel="stylesheet" href="{% static 'css/infomat.css' %}">
      {% endcompress %}
    {% endblock %}

  </head>

  <body>
    <div id="main-container">
      <div id="body">
        {% block navigation-panel %}
        {% endblock navigation-panel %}


          <div class="col-sm-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
                {% endfor %}
            {% endif %}

            {% block content %}

            {% endblock content %}
          </div>


        {% block javascript %}
          <script src="{% static 'library/jquery/dist/jquery.min.js' %}"> </script>
          <script src="{% static 'library/bootstrap/dist/js/bootstrap.min.js' %}"></script>
          <script src="{% static 'library/jquery.maskedinput/dist/jquery.maskedinput.min.js' %}"></script>
          <script src="{% static 'library/jquery-nice-select/js/jquery.nice-select.min.js' %}"></script>
          <script src="{% static 'library/keyboard/docs/js/jquery-ui.min.js' %}"></script>
          <script src="{% static 'library/keyboard/dist/js/jquery.keyboard.min.js' %}"></script>
          <script src="{% static 'js/infomat.js' %}"></script>
          {% compress js %}

          {% endcompress %}
        {% endblock javascript %}

        {% block modal %}{% endblock modal %}
      </div> <!-- id=body-->

    </div> <!-- /main-container -->
  </body>
</html>

webreg/infomat_writer/templates/infomat_writer/confirm.html
{% extends 'infomat_writer/base.html' %}
{% block content %}
<div class="container-fluid has-frame">
  <form>
    <div>
      <h2>{{patient.last_name | upper}} {{patient.middle_name | upper}} ЭТО ВЫ?</h2>
      <p> Нажимая "Да. ..." Вы автоматически принимаете <a href="{% url 'infomat_writer:agreement' %}">правила обработки даных</a> ФГБУ ФСНКЦ ФМБА России</p>
    </div>
    <div class="col-md-10 col-md-offset-1">
      <div class="hidden-xs col-xs-6">
        <button type="submit" formmethod="get" formaction="{% url 'infomat_writer:input_second_step' %}" class="btn btn-primary btn-lg col-xs-12">Да. Продолжить запись</button>
      </div>
      <div class="hidden-xs col-xs-6">
        <button type="submit" formethod="post" formaction="{% url 'infomat_writer:account_logout' %}" class="btn btn-primary btn-lg col-xs-12">Нет. Ввести заново</button>
      </div>
      <div class="visible-xs col-xs-6">
        <button type="submit" formmethod="get" formaction="{% url 'infomat_writer:input_second_step' %}" class="btn btn-primary btn-lg col-xs-12">Да</button>
      </div>
      <div class="visible-xs col-xs-6">
        <button type="submit" formethod="post" formaction="{% url 'infomat_writer:account_logout' %}" class="btn btn-primary btn-lg col-xs-12">Нет</button>
      </div>
    </div>
      <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}"/>
  </form>
</div>
{% endblock content%}

webreg/infomat_writer/templates/infomat_writer/input_second_step.html
{% extends 'infomat_writer/base.html' %}

{% load flatblocks %}
{% load static %}
{% load compress %}

{% block content %}
<div class="container-fluid has-frame">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <h3>ВЫБЕРИТЕ ДАТУ И ВРЕМЯ</h3>
    <form id="input_form_2" method="POST" action="{% url 'infomat_writer:input_second_step' %}">
      {% csrf_token %}
      <div id="department-form" class="form-group" style="display: none;">
        <label for="id_department" class="control-label requiredField">
          Подразделение <span class="asteriskField">*</span>
        </label>
        <div>
          <select class="select form-control" id="id_department" name="department" required>
            <option disabled selected value=-1> -- Выберите подразделение -- </option>
            {% for department in departments %}
              <option value="{{department.id}}">{{department.name}}, {{department.address}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div id="speciality-form" class="form-group">
        <label for="id_speciality" class="control-label requiredField">
          Специальность <span class="asteriskField">*</span>
        </label>
        <select id="id_speciality" type="text" class="form-control" name="speciality" required>
          <option disabled selected value=-1> -- Выберите специальность -- </option>
        </select>
        <button id="speciality_question" class="hidden-xs btn btn-primary question-mark" type="button" data-toggle="modal" data-target="#speciality_help_modal">?</button>
        <div id="speciality_help_modal" class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
             <div class="modal-body">
                {% flatblock "speciality_help" %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="speciality-comment-message" class="alert" style="display: none">
      </div>
      <div id="specialist-form" class="form-group" style="display:none">
        <label for="id_specialist" class="control-label requiredField">
          Специалист <span class="asteriskField">*</span>
        </label>
        <select id="id_specialist" class="form-control" name="specialist" required>
          <option disabled selected value=-1> -- Выберите специалиста -- </option>
        </select>
        <button id="specialist_question" class="hidden-xs btn btn-primary question-mark" type="button" data-toggle="modal" data-target="#specialist_help_modal">?</button>
         <div id="specialist_help_modal" class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
             <div class="modal-body">
                {% flatblock "specialist_help" %}
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div id="timetable-form" class="row container-fluid form-group" style="display: none">
        <label>
          Выберите дату и время <span class="asteriskField">*</span>
        </label>
        <div class="has-border">
          <div id="id_selected_datetime" style="display: none;">
            <div class="row">
	            <label class="col-sm-5">
		            Дата приема:
              </label>
              <div class="col-sm-5 form-value">
                <div  id="id_selected_date">
                </div>
                <div  id="id_selected_dayweek">
                </div>
              </div>
            </div>
            <div class="row">
	            <label class="col-sm-5">
		            Время приема:
              </label>
              <div class = "col-xs-12 col-sm-5 form-value" id="id_selected_time">
              </div>
            </div>
          </div>
          <div class="row">
              <div class="col-sm-6 col-sm-offset-3">
                <button id="show-timetable-button" type="button" class="btn btn-primary btn-block">
                    ВЫБРАТЬ
                </button>
              </div>
          </div>
        </div>
        <input id="id_cell" type="hidden" name="cell">
        <div  class="modal fade" id="timetable-modal-window">
          <div>
            <div class="modal-content">
              <div class="modal-header">
                <div class="col-xs-4 col-xs-offset-4">
                  <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">
                    <span class="glyphicon glyphicon-chevron-left"></span>Назад
                  </button>
                </div>
              </div>
              <div id="id_loading_message" style="display: none">
                <h4>Загрузка расписания...</h4>
                <div class="loader">
                </div>
              </div>
              <div class="modal-body" id="id_timetable">
              </div>
              <div class="modal-footer">
                <div class="col-xs-4 col-xs-offset-4">
                  <button type="button" class="btn btn-primary btn-block" data-dismiss="modal">Закрыть</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div id="error-message" class="alert alert-danger" style="display:none;">
      </div>
     <div class="row col-xs-12 col-sm-6 col-sm-offset-3 form-btn">
      <a id="back-button" class="btn btn-primary btn-lg btn-block" href="{% url 'infomat_writer:account_logout' %}"><span class="glyphicon glyphicon-chevron-left"></span> Назад</a>
      <button type="submit" id="write-button" class="btn btn-primary btn-lg btn-block" style="display: none">Записаться</button>
     </div>
      </form>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
{{ block.super}}
  <script type="text/javascript" src="{% static 'library/jquery-touchswipe/jquery.touchSwipe.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'library/jcarousel/dist/jquery.jcarousel.min.js' %}"></script>
  {% compress js %}
  <script type="text/javascript" src="{% static 'js/timetablecarousel.js' %}"></script>
  <script src="{% static '/js/input_second_form_control_infomat.js' %}"></script>
  <script>
  $( function(){
    $('#id_department').val({{ department_id }});
    window.getSpecializations({{ department_id }});

  });
  </script>
  {% endcompress %}
{% endblock javascript%}

webreg/infomat_writer/templates/infomat_writer/logout.html
{% extends "infomat_writer/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}Выход{% endblock %}

{% block content %}


<div class="container-fluid has-frame">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <h3>ВЫХОД</h3>
        <p>Вы действительно хотите выйти?</p>
        <div class="container-fluid">
            <div class="row">
                <form method="post" action="{% url 'infomat_writer:account_logout' %}">
                  {% csrf_token %}
                  <button class="col-xs-4 col-sm-5 btn btn-danger" type="submit">Выйти</button>
                    <a href= "{% url 'infomat_writer:input_second_step' %}" class="col-xs-offset-1 col-xs-6 col-sm-5 btn btn-primary">
                    Продолжить запись
                    </a>
                </form>
            </div>
        </div>
    </div>
  </div>

</div>
{% endblock content %}

webreg/infomat_writer/templates/infomat_writer/talon_row.html
<div class="row">
  <label class="col-xs-12 col-sm-4">{{label}}</label>
  <div class="col-xs-10 col-xs-offset-2 col-sm-6 form-value">
    {{value}}
  </div>
</div>