webreg/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views import defaults as default_views
from django.conf.urls.static import static
from main.urls import apiurlpatterns as mainapiurlpatterns
from main.urls import urlpatterns as main_urlpatterns
from patient_writer.urls import apiurlpatterns as patient_writer_apiurlpatterns

apiurlpatterns = mainapiurlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^pwriter/', include('patient_writer.urls', namespace="patient_writer")),
    url(r'^infomat_writer/', include('infomat_writer.urls', namespace="infomat_writer")),
    url(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'api/', include(apiurlpatterns)),
    url(r'api/pwriter/', include(patient_writer_apiurlpatterns))
] + main_urlpatterns + \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

webreg/infomat_writer/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.decorators.clickjacking import xframe_options_exempt
from infomat_writer.views import PatientWriteFirstStep, PatientWriteSecondStep, Confirm,\
    TalonView, logout






urlpatterns = [
    url(r'^input_first_step/(?P<department>[\d+]+)/$', xframe_options_exempt(PatientWriteFirstStep.as_view()), name="input_first_step"),
    url(r'^input_second_step/$', xframe_options_exempt(PatientWriteSecondStep.as_view()), name="input_second_step"),
    url(r'^confirm/$', xframe_options_exempt(Confirm.as_view()), name="confirm"),
    url(r'^agreement/$', xframe_options_exempt(TemplateView.as_view(template_name="infomat_writer/agreement.html")), name="agreement"),
    url(r'^talon/$', xframe_options_exempt(TalonView.as_view()), name="talon"),
    url(r'^accounts/logout/$', xframe_options_exempt(logout),
        {
            'template_name': "infomat_writer/logout.html",
        },
        name="account_logout"),
]

webreg/main/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from django.contrib.auth.views import login, logout, password_reset
from main.api.timetable import SpecialistsFreeCells, SpecialistAllCells
from main.forms import AuthenticationForm
from main.views import MainView

apiurlpatterns = [
    url(r'timetable/free/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})$', SpecialistsFreeCells.as_view()),
    url(r'timetable/free/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})/(\d{1,4})$', SpecialistsFreeCells.as_view()),
    url(r'timetable/(\d{1,4})/(\d{4}-\d{2}-\d{2})/(\d{4}-\d{2}-\d{2})$', SpecialistAllCells.as_view())
]


urlpatterns = [
    url(r'^$', MainView.as_view(), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),
    url(r'^accounts/login', login, {'template_name': "account/login.html",
                                    'authentication_form': AuthenticationForm,
                                    'extra_context': {'redirect_field_value': '/',
                                                      'redirect_field_name': 'next'}}, name="account_login"),
    url(r'^accounts/logout', logout, {'template_name': "account/logout.html",
                                      'extra_context': {'redirect_field_value': '/',
                                                        'redirect_field_name': 'next'}
                                      }, name="account_logout"),
]

webreg/patient_writer/accounts/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import views as auth_views
from patient_writer.accounts.forms import PatientRegistrationForm
from patient_writer.accounts.views import PatientRegistrationView, PatientActivationView, login, logout, \
    LogOutConfirmView

urlpatterns = [
    url(r'^accounts/register/$', PatientRegistrationView.as_view(
            disallowed_url=reverse_lazy('patient_writer:registration_disallowed'),
            template_name='patient_writer/accounts/register.html',
            form_class=PatientRegistrationForm,
            success_url=reverse_lazy('patient_writer:registration_complete')
            ),
        name="registration"),
    url(r'^accounts/register/complete',
        TemplateView.as_view(template_name="patient_writer/accounts/registration_complete.html"),
        name="registration_complete"),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', PatientActivationView.as_view(
            template_name='patient_writer/accounts/activate.html',
            ),
        name='registration_activate'),
    url(r'^accounts/activate/complete/$', TemplateView.as_view(
        template_name='patient_writer/activation_complete.html'),
        name='activation_complete'),

    url(r'^accounts/login', login,
        {
            'template_name': "patient_writer/accounts/login.html",
            'authentication_form': AuthenticationForm,
            'extra_context': {
                'redirect_field_value': reverse_lazy('patient_writer:input_second_step'),
                'redirect_field_name': 'next'
            }
        },
        name="account_login"),

    url(r'^accounts/logout/$', logout,
        {
            'template_name': "patient_writer/accounts/logout.html",
            'extra_context': {
                'redirect_field_value': reverse_lazy('patient_writer:input_first_step'),
                'redirect_field_name': 'next'
            }
        },
        name="account_logout"),

    url(r'^accounts/logout-confirm/$', LogOutConfirmView.as_view(), name="account_logout_confirm"),

    url(r'^password/reset/$',
        auth_views.password_reset,
        {'post_reset_redirect': 'patient_writer:auth_password_reset_done',
         'email_template_name': 'patient_writer/accounts/email/password_reset_email.html',
         'html_email_template_name': 'patient_writer/accounts/email/password_reset_email.html',
         'subject_template_name': 'patient_writer/accounts/email/password_reset_subject.txt',
         'template_name': 'patient_writer/accounts/password_reset_form.html'},
        name='auth_password_reset'),
    url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm,
        {'post_reset_redirect': 'patient_writer:auth_password_reset_complete',
         'template_name': 'patient_writer/accounts/password_reset_confirm.html'},
        name='auth_password_reset_confirm'),
    url(r'^password/reset/complete/$',
        auth_views.password_reset_complete,
        {'template_name': 'patient_writer/accounts/password_reset_complete.html'},
        name='auth_password_reset_complete'),
    url(r'^password/reset/done/$',
        auth_views.password_reset_done,
        {'template_name': 'patient_writer/accounts/password_reset_done.html'},
        name='auth_password_reset_done'),
]

webreg/patient_writer/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from patient_writer.views import PatientWriteFirstStep, PatientWriteSecondStep, Confirm,\
    SpecialistTimeTable, TalonView, TalonPdf, AppointmentListView, HelpView, AppointmentDetailView,\
    CancelAppointmentView, SelectClinicView
from patient_writer.api.api import AvailableSpecialists, AvailableSpecializaionsForDepartment
from patient_writer.accounts.urls import urlpatterns as account_urlpatterns


apiurlpatterns = [
    url(r'^avail_specialists/(?P<department_id>\d+)/(?P<specialization_id>\d+)', AvailableSpecialists.as_view()),
    url(r'^specializations_for_dep/(\d+)', AvailableSpecializaionsForDepartment.as_view()),
]


urlpatterns = [
    url(r'^input_first_step/', PatientWriteFirstStep.as_view(), name="input_first_step"),
    url(r'^select_clinic/', SelectClinicView.as_view(), name="select_clinic"),
    url(r'^input_second_step/$', PatientWriteSecondStep.as_view(), name="input_second_step"),
    url(r'^agreement/$', TemplateView.as_view(template_name="patient_writer/agreement.html"), name="agreement"),
    url(r'^confirm/$', Confirm.as_view(), name="confirm"),
    url(r'^timetable/specialist/(\d+)', SpecialistTimeTable.as_view()),
    url(r'^talon/$', TalonView.as_view(), name="talon"),
    url(r'^talon_pdf/(\d+)$', TalonPdf.as_view(), name="talon_pdf"),
    url(r'^appointment_list/', AppointmentListView.as_view(), name="appointment_list"),
    url(r'^help/$', HelpView.as_view(), name="help"),
    url(r'^cancel_appointment/(?P<pk>\d+)', CancelAppointmentView.as_view(), name="cancel_appointment"),
    url(r'^appointment_detail/(?P<pk>\d+)', AppointmentDetailView.as_view(), name="appointment_detail"),
]

urlpatterns += account_urlpatterns

webreg/patient_writer/accounts/models.py
from registration.models import RegistrationProfile
from django.template.loader import render_to_string
from django.conf import settings


class PatientRegistrationProfile(RegistrationProfile):
    def send_activation_email(self, site):
        """
        Send an activation email to the user associated with this
        ``RegistrationProfile``.

        """
        ctx_dict = {'activation_key': self.activation_key,
                    'expiration_days': settings.ACCOUNT_ACTIVATION_DAYS,
                    'user': self.user,
                    'site': site}
        subject = render_to_string('patient_writer/accounts/email/activation_email_subject.txt',
                                   ctx_dict)
        # Force subject to a single line to avoid header-injection
        # issues.
        subject = ''.join(subject.splitlines())
        message = render_to_string('patient_writer/accounts/email/activation_email.html',
                                   ctx_dict)
        self.user.email_user(subject, '', settings.DEFAULT_FROM_EMAIL, html_message=message)

    class Meta:
        proxy = True

webreg/patient_writer/accounts/views.py
import logging
from registration.views import RegistrationView, ActivationView
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.views import login as DjangoLogin, logout as DjangoLogout
from django.http import HttpResponse
from django.views.generic import TemplateView
from main.logic import *
from patient_writer.accounts.forms import PatientRegistrationForm
from patient_writer.accounts.models import PatientRegistrationProfile
from loghandle.models import UserAction as action


class Actions:
    REGISTER = "Пользователь зарегистрировался"
    ACTIVE = "Пользователь стал активным"
    LOGIN = "Пользоваетль залогинился"
    LOGOUT = "Пользователь вышел"
    WRONG_PASSWORD = "Неверный пароль"

log = logging.getLogger("webreg")


class PatientRegistrationView(RegistrationView):
    disallowed_url = reverse_lazy('patient_writer:registration_disallowed')
    template_name = 'patient_writer/accounts/register.html',
    form_class = PatientRegistrationForm,
    success_url = reverse_lazy('patient_writer:registration_complete')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        self.site = get_current_site(request)

        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def register(self, form):
        site = self.site
        new_user = PatientRegistrationProfile.objects.create_inactive_user(form, site)
        cleaned_data = form.cleaned_data
        try:
            profile = UserProfile.objects.get(name=settings.PATIENT_WRITER_PROFILE)
            profile.user.add(new_user)
            try:
                patient = Patient.objects.get(pk=cleaned_data['patient_id'])
                try:
                    update_patient_phone_number(patient, cleaned_data['phone'])
                except PatientError as er:
                    log.error("Ошибка при обновлении телефона" + str(er) + str(cleaned_data))
                    return HttpResponse(status=500)
                patient.user = new_user
                patient.save()
                try:
                    clinic = Clinic.objects.get(pk=cleaned_data['clinic_id'])
                    patient.clinic_attached = clinic
                except Clinic.DoesNotExist:
                    log.error("Ошибка при регистрации. Не найден пациент не найдено мед. учреждение"
                              + str(cleaned_data))
            except Patient.DoesNotExist:
                log.error("Ошибка при регистрации. Не найден пациент" + str(cleaned_data))
                return HttpResponse(status=500)
        except UserProfile.DoesNotExist:
            raise ImproperlyConfigured("Необходимо настроить профиль пользователя для записи на прием")
        new_user.save()
        action.log(Actions.REGISTER, user_id=new_user.id)
        return new_user

    def get_success_url(self, user):
        return self.success_url, (), {}


class PatientActivationView(ActivationView):

    def activate(self, request, activation_key):
        activated_user = PatientRegistrationProfile.objects.activate_user(activation_key)
        if activated_user:
            action.log(Actions.ACTIVE, user_id=activated_user.id)
        return activated_user

    def get_success_url(self, user):
        return reverse_lazy('patient_writer:activation_complete'), (), {}


def login(request, *args, **kwargs):
    http = DjangoLogin(request, *args, **kwargs)
    if request.method == 'GET':
        patient_id = request.session.get('patient_id', None)
        if patient_id:
            return redirect('patient_writer:input_second_step')

    if request.method == 'POST':
        try:
            user = request.user
            if user.id:
                patient = Patient.objects.get(user_id=user.id)
                request.session['patient_id'] = patient.id
                request.session['clinic_id'] = patient.clinic_attached.id
                # вызов функции для синхронизации qqc кумса
                find_patient_by_polis_number(
                    patient.polis_number,
                    patient.birth_date,
                    patient.polis_seria,
                )
        except Patient.DoesNotExist:
            pass
        if user.id:
            action.log(Actions.LOGIN)
        else:
            action.log(
                Actions.WRONG_PASSWORD,
                info={
                    'username': http.context_data['form'].cleaned_data['username'],
                    'password': http.context_data['form'].cleaned_data['password'],
                }
            )

    return http


class LogOutConfirmView(TemplateView):
    template_name = 'patient_writer/accounts/logout.html'


def logout(request, *args, **kwargs):
    kwargs.update({'next_page': 'patient_writer:input_first_step'})
    action.log(Actions.LOGOUT)
    http = DjangoLogout(request, *args, **kwargs)
    try:
        del request.session['patient_id']
        del request.session['clinic_id']
    except KeyError:
        pass
    return http

webreg/patient_writer/accounts/templates/patient_writer/accounts/activate.html
{% extends "patient_writer/base.html" %}
{% load static %}


{% block content %}
    <h1>Активация.</h1>
    <p>Добрый день, {{ account }}!</p>
    <p>Ваша учетная запись активирована. <a href="{% url 'patient_writer:account_login' %}">Заходите</a> на сайт.</p>
{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/activation_complete.html
{% extends "patient_writer/base.html" %}
{% load static %}


{% block content %}
    <h1>Поздравляем!</h1>
    <p>Ваш личный кабинет активирован.</p>
{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/login.html
{% extends "patient_writer/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}Вход{% endblock %}

{% block content %}
<div class="container-fluid has-frame">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <h3>ВХОД</h3>
        <form class="login" method="POST" action="{% url 'patient_writer:account_login' %}">
          {% csrf_token %}
          {{ form|crispy }}
          {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
          {% endif %}
          <a class="button secondaryAction" href="{% url 'patient_writer:auth_password_reset' %}">Забыли пароль?</a>
          <div class="span12"><br/></div>
          <button class="row btn btn-primary btn-lg btn-block form-btn" type="submit">Войти</button>
        </form>
    </div>
  </div>

</div>
{% endblock content %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/logout.html
{% extends "patient_writer/base.html" %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}Выход{% endblock %}

{% block content %}


<div class="container-fluid has-frame">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
        <h3>ВЫХОД</h3>
        <p>Вы действительно хотите выйти?</p>
        <div class="container-fluid">
            <div class="row">
                <form method="post" action="{% url 'patient_writer:account_logout' %}">
                  {% csrf_token %}
                  <button class="col-xs-4 col-sm-5 btn btn-danger" type="submit">Выйти</button>
                    <a href= "{% url 'patient_writer:input_second_step' %}" class="col-xs-offset-1 col-xs-6 col-sm-5 btn btn-primary">
                    Продолжить запись
                    </a>
                </form>
            </div>
        </div>
    </div>
  </div>

</div>
{% endblock content %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/password_reset_complete.html
{% extends "patient_writer/base.html" %}

{% block title %}
    Восстановление пароля завершено
{% endblock %}

{% block content %}
    <h1> Восстановление пароля завершено.</h1>
    <p> Новый пароль установлен.</p>
    <p> Теперь вы можете <a href="{% url 'patient_writer:account_login'%}">войти</a></p>
{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/password_reset_confirm.html
{% extends "patient_writer/base.html" %}

{% block title %}
    Восстановление пароля
{% endblock %}


{% block content %}
<div class="container-fluid has-frame">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      {% if validlink %}
      <h3>Введите новый пароль</h3>
      <form method="POST">
        {% include 'form_field_generic.html' %}
        <div class="col-xs-12  col-sm-6 col-sm-offset-3 form-btn">
          <button class="row btn btn-primary btn-lg btn-block" type="submit"> Сменить пароль </button>
        </div>
      </form>
      {% else %}
        <h1>Смена пароля невозможна!</h1>
        <p>Ссылка на смену пароля недействительна... Пожалуйста попробуйте осуществить операцию заново.</p>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/password_reset_done.html
{% extends "patient_writer/base.html" %}

{% block title %}
    Восстановление пароля
{% endblock %}


{% block content %}
<div class="container-fluid has-frame">
  <div class="row">
    <h1>Восстановление пароля.</h1>
    <p>Мы выслали Вам инструкции на почтовый ящик, указанный в личном кабинете.</p>
    <p>Если Вам не приходило электронное письмо, то проверьте правильность введенного почтового ящика и проверьте папку со спамом.</p>
  </div>
</div>

{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/password_reset_form.html
{% extends "patient_writer/base.html" %}
{% load static %}
{% load compress %}

{% block custom_css %}
    {% compress css %}
    <link rel="stylesheet" href="{% static 'registration/css/registration.css' %}"/>
    {% endcompress %}
{% endblock %}

{% block content %}

<div class="container-fluid has-frame">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h3>Сброс пароля</h3>
      <form method="POST">
        {% include 'form_field_generic.html' %}
        <div class="col-xs-12  col-sm-6 col-sm-offset-3 form-btn">
          <button class="row btn btn-primary btn-lg btn-block" type="submit"> Подтвердить адрес </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/register.html
{% extends 'patient_writer/base.html' %}
{% load compress %}
{% load static %}
{% block content %}
<div class="container-fluid has-frame">
  <div class="row">
    <div class="col-xs-12 col-sm-8 col-sm-offset-2">
      <h3>РЕГИСТРАЦИЯ</h3>
      <form id="registration_form" method="POST" action="{% url 'patient_writer:registration' %}">
        {% include 'form_field_generic.html' %}
        <div class="col-xs-12  col-sm-6 col-sm-offset-3 form-btn">
          <button class="row btn btn-primary btn-lg btn-block" type="submit"> Регистрация </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block javascript %}
    {{ block.super }}
{% compress js %}
<script src="{% static '/js/input_first_form_control.js' %}"></script>
{% endcompress %}

{% endblock %}

webreg/patient_writer/accounts/templates/patient_writer/accounts/registration_complete.html
{% extends "patient_writer/base.html" %}
{% load static %}


{% block content %}
    <h1>Регистрация завершена.</h1>
    <p>Для активации личного кабинета в ближайшие 30 минут Вам будет отправлено письмо на электронную почту.</p>
    <p>В письме будут инструкции по активации.</p>
    <p>До завершения активации вход в личный кабинет невозможен.</p>
{% endblock %}